services:
    wyze-bridge:
        container_name: wyze-bridge
        restart: unless-stopped
        image: mrlt8/wyze-bridge:latest
        ports:
            - 1935:1935 # RTMP
            - 8554:8554 # RTSP
            - 8888:8888 # HLS
            - 8889:8889 #WebRTC
            - 8189:8189/udp # WebRTC/ICE
            - 5001:5000 # WEB-UI
        environment:
            - WYZE_EMAIL=
            - WYZE_PASSWORD=
            - API_ID= # Wyze API ID
            - API_KEY= # Wyze API Key

            - WB_AUTH=False
            - FRESH_DATA=True

            # Recording settings
            - TZ=America/Vancouver
            - RECORD_ALL=True
            - RECORD_PATH=/record/{cam_name}/%Y-%m-%d
            - RECORD_FILE_NAME={cam_name}_%H_%M_%S
            - RECORD_LENGTH=60s

        volumes:
            - /local/path/:/record/
#        deploy: #GPU support
#            resources:
#                reservations:
#                    devices:
#                        - driver: nvidia
#                          count: 1
#                          capabilities: [gpu]



