services:
    wyze-bridge:
        container_name: wyze-bridge
        restart: unless-stopped
        image: mrlt8/wyze-bridge:latest # GPU support with latest-hw
        ports:
            - 1935:1935 # RTMP
            - 8554:8554 # RTSP
            - 8888:8888 # HLS
            - 8889:8889 #WebRTC
            - 8189:8189/udp # WebRTC/ICE
            - 5001:5000 # WEB-UI
        environment:
            - WYZE_EMAIL=gnxilef@gmail.com
            - WYZE_PASSWORD=AeIuo7g13241
            - API_ID=84dc0ab9-691b-40b0-843e-db1c8c2c1a8c # Wyze API ID
            - API_KEY=1xRo6IVWyM3PfsZmJVWjQgGBZZD59DRxczcxdYrIlKQNevoVYoUWdMiCjazD # Wyze API Key
            - FILTER_NAMES=driveway
            - WB_AUTH=False
            - FRESH_DATA=True
            - ROTATE_DOOR=True
            - H264_ENC=h264_nvenc #GPU support
            # Recording settings
            - TZ=America/Vancouver
            - RECORD_DRIVEWAY=True
            - RECORD_PATH=/record/{cam_name}/%Y-%m-%d
            - RECORD_FILE_NAME={cam_name}_%H_%M_%S
            - RECORD_LENGTH=60s
        networks:
            - wyze-bridge-network
        # Recording settings
        volumes:
            - C:\Users\Felix\Desktop\Camera\videos:/record/
        deploy: #GPU support
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          count: 1
                          capabilities: [gpu]

    recorder:
        container_name: wyze-recorder
        build:
            context: ../recorder
            dockerfile: Dockerfile
        volumes:
            - C:\Users\Felix\Desktop\Camera\videos:/app/videos
            - C:\Users\Felix\Desktop\Camera\clips:/app/clips
            - C:\Users\Felix\Desktop\Camera\db:/app/data


networks:
    wyze-bridge-network:

